name: "AWS Environment Info"
description: 'Based on the input of the environment type, the relevant environmental information is provided as output.'

inputs:
  aws_environment:
    required: true
    description: 'The AWS Environment'
  aws_dev_account_id:
    required: true
    description: 'The AWS Dev Account ID'
  aws_test_account_id:
    required: true
    description: 'The AWS Test Account ID'
  aws_prod_account_id:
    required: true
    description: 'The AWS Prod Account ID'
outputs:
  aws_account_id:
    value: $AWS_ACCOUNT_ID

runs:
  using: composite
  steps:
    - if: inputs.aws_environment == 'dev'
      name: dev-environment
      shell: bash
      run: echo "AWS_ACCOUNT_ID=inputs.aws_dev_account_id" >> $GITHUB_ENV

    - if: inputs.aws_environment == 'test'
      name: test-environment
      shell: bash
      run: echo "AWS_ACCOUNT_ID=inputs.aws_test_account_id" >> $GITHUB_ENV

    - if: inputs.aws_environment == 'prod'
      name: prod-environment
      shell: bash
      run: echo "AWS_ACCOUNT_ID=inputs.aws_prod_account_id" >> $GITHUB_ENV
